# Generated by Django 4.2.16 on 2024-10-07 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(choices=[('housing', 'Housing & Real Estate'), ('education', 'Education'), ('healthcare', 'Healthcare')], max_length=20)),
                ('investment_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estimated_return', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField()),
                ('public_feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
